/* Zoé Axon — interactive explainer · MOCK DATA (no real systems are called)
   step shape consumed by the engine:
   { id, type, title, service, output, durationMs,
     chat?:{from:'user'|'zoe', text}, inputs?:{...}, checked?:'', guard?:'',
     branch?:'label shown for a choice',
     hitl?:{ prompt, onApprove:'stepId', onReject:'stepId' },
     agents?:[{service,title,output}],   // when type==='parallel'
     status?:'fail' }                    // optional forced failure -> compensation+escalate
   type ∈ tool_call | llm_call | agent | script | human_approval | choice | parallel | terminal
*/
const PLANES = [
  { id:'channels',  name:'Channels',          plain:'How people reach Zoé',
    items:['Xpin voice','Text chat','Web','Email'], hosting:'either',
    detail:'Where a request comes in. Voice and chat are interchangeable — the same brain handles both.' },
  { id:'brain',     name:'The Brain (Logic)',  plain:'Understands & decides', highlight:true, hosting:'on-prem',
    items:['Reasoning','SOP Engine','Orchestrator','Guardrails'],
    detail:'Reads the request, picks the matching recipe, runs its steps in order, and enforces the safety checks. The SOP Engine is the heart of the whole system.' },
  { id:'knowledge', name:'Knowledge & Memory', plain:'What Zoé knows', hosting:'on-prem',
    items:['Runbooks / RAG','IT inventory (CMDB)','Conversation memory'],
    detail:'Looks up how-to knowledge and the live list of devices, software and owners (the CMDB).' },
  { id:'connectors',name:'Connectors',         plain:'The systems it acts on', hosting:'cloud',
    items:['ServiceNow','Active Directory','Entra / Okta','Intune','Zscaler','Nexthink / DEX','M365'],
    detail:'The real IT tools the company already uses. Zoé reaches them through typed, audited adapters that can be swapped per client.' },
  { id:'model',     name:'Model plane',        plain:'The AI itself', hosting:'on-prem',
    items:['Language models','Speech (voice)','Embeddings'],
    detail:'The AI that does the understanding, plus speech for voice. Self-hosted so sensitive data stays in-house.' },
  { id:'data',      name:'Data & Audit',       plain:'Memory & the record', hosting:'on-prem',
    items:['Database','Immutable audit log → SIEM'],
    detail:'Stores tickets & state, and keeps an unchangeable record of every action for security and compliance.' },
];
const SERVICES = {
  reasoning:{ label:'AI',               color:'#0EA5E9', plane:'brain' },
  sop:      { label:'SOP Engine',       color:'#1F5CEA', plane:'brain' },
  human:    { label:'Human approver',   color:'#D97706', plane:'brain' },
  servicenow:{label:'ServiceNow',       color:'#16A34A', plane:'connectors' },
  ad:       { label:'Active Directory', color:'#1F5CEA', plane:'connectors' },
  entra:    { label:'Entra / Okta',     color:'#1F5CEA', plane:'connectors' },
  intune:   { label:'Intune',           color:'#1F5CEA', plane:'connectors' },
  zscaler:  { label:'Zscaler',          color:'#1F5CEA', plane:'connectors' },
  dex:      { label:'Nexthink / DEX',   color:'#0D9488', plane:'connectors' },
  m365:     { label:'M365',             color:'#1F5CEA', plane:'connectors' },
  license:  { label:'License Mgr',      color:'#7C3AED', plane:'connectors' },
};
const MODULARITY = {
  core:'Zoé Core — the SOP engine, the safety gate, the audit. Identical for every client.',
  rings:[
    { id:'channels',  name:'Channels',     note:'Plug in Xpin voice, chat, web — whatever the client uses.' },
    { id:'recipes',   name:'Recipe packs', note:'Ship the shared library of common recipes; add the client’s own.' },
    { id:'connectors',name:'Connectors',   note:'Swap ServiceNow for another ticket tool, or their identity/endpoint systems.' },
  ],
  profiles:['Hybrid (core on your servers + cloud tools)','Full cloud'],
  line:'A new client = pick a profile, plug in their systems, load their recipes. No rebuild.'
};
const SCENARIOS = [
  /* 1 ───────────────── PASSWORD RESET (fully automatic) */
  { id:'password_reset', title:'Password reset', icon:'🔑', category:'Identity', tier:'L1', autonomy:'auto',
    channel:'chat', user:{name:'Sarah K.', id:'sarah.k', device:'SARAH-LT-04'},
    intent:'Password reset', confidence:0.98,
    variables:[ {k:'user', v:'sarah.k', src:'who raised the ticket'},
                {k:'device', v:'SARAH-LT-04', src:'IT inventory (CMDB)'},
                {k:'verify device', v:'iPhone 15', src:'Entra (her enrolled phone)'} ],
    sopId:'password_reset', sopVersion:'2',
    sopJson:`{ "sop_id":"password_reset","version":"2","autonomy":{"mode":"auto","min_confidence":0.9},
  "states":[
    {"id":"fetch","type":"tool_call","tool":"servicenow.get_incident","next":"verify"},
    {"id":"verify","type":"tool_call","tool":"entra.send_mfa_push","next":"confirm"},
    {"id":"confirm","type":"tool_call","tool":"entra.verify_mfa","catch":"escalate","next":"reset"},
    {"id":"reset","type":"tool_call","tool":"ad.reset_password","guards":{"idempotency_key":"reset:{{ticket}}"},"next":"unlock"},
    {"id":"unlock","type":"tool_call","tool":"ad.unlock_account","next":"close"},
    {"id":"close","type":"terminal","status":"success"} ] }`,
    steps:[
      {id:'fetch', type:'tool_call', service:'servicenow', title:'Open the ticket', durationMs:1200,
        chat:{from:'user', text:"Hi, I can't log into my laptop — my password isn't working."},
        output:'Ticket INC-4821 created', inputs:{user:'sarah.k'}, checked:'New incident logged in ServiceNow'},
      {id:'verify', type:'tool_call', service:'entra', title:"Send a verification push to Sarah's phone", durationMs:1600,
        chat:{from:'zoe', text:"Morning Sarah — happy to help. I've sent a quick approval to your phone, please tap Approve."},
        output:'Push sent to iPhone 15', inputs:{user:'sarah.k', device:'iPhone 15'}, guard:'Identity must be proven before any change'},
      {id:'confirm', type:'tool_call', service:'entra', title:'Confirm she approved it', durationMs:1400,
        output:'Approved at 09:12:04', checked:'Identity verified ✓'},
      {id:'reset', type:'tool_call', service:'ad', title:'Reset the password', durationMs:1100,
        chat:{from:'zoe', text:"Verified — resetting your password and unlocking the account now."},
        output:'Temporary password set (expires in 24h)', inputs:{user:'sarah.k'}, guard:'Reversible · only affects 1 account'},
      {id:'unlock', type:'tool_call', service:'ad', title:'Unlock the account', durationMs:900,
        output:'Account unlocked', checked:'Force change at next sign-in'},
      {id:'close', type:'terminal', service:'servicenow', title:'Close the ticket', durationMs:1000,
        chat:{from:'zoe', text:"All set — a temporary password is on its way to your phone. You'll set a new one when you sign in."},
        output:'Resolved · code: Solved (Permanently)'},
    ],
    outcome:{ ticket:'INC-4821', resolution:'Solved (Permanently)', elapsedSec:28, automationPct:100, trueResolution:true,
      logs:['Ticket created','Matched recipe: password_reset','Identity verified','Account unlocked','Resolved in 28s — no human needed'] } },
  /* 2 ───────────────── LICENCE EXPIRED (automatic + needs a manager's OK) — the worked example */
  { id:'license_expired', title:'Licence expired', icon:'📄', category:'Software', tier:'L2', autonomy:'auto+approval',
    channel:'chat', user:{name:'Omar A.', id:'omar.a', device:'OMAR-WS-02'},
    intent:'Licence expired', confidence:0.95,
    variables:[ {k:'product', v:'AutoCAD', src:'the ticket / IT inventory'},
                {k:'user', v:'omar.a', src:'who raised the ticket'},
                {k:'cost', v:'£480 / year', src:'License Manager'},
                {k:'auto-approve limit', v:'£500', src:'company policy'} ],
    sopId:'license_expired', sopVersion:'3',
    sopJson:`{ "sop_id":"license_expired","version":"3","category":"Software/License",
  "trigger":{"intent":"license_expired"},
  "variables":{ "product":{"from":"ticket.cmdb_ci"}, "user":{"from":"ticket.caller"} },
  "autonomy":{"mode":"auto","min_confidence":0.85},
  "states":[
    {"id":"fetch","type":"tool_call","tool":"servicenow.get_incident","next":"check"},
    {"id":"check","type":"tool_call","tool":"license.get_status","next":"decide"},
    {"id":"decide","type":"choice","choices":[
        {"if":"!renewable","next":"escalate"},
        {"if":"licence_spend","next":"approve"}], "default":"renew"},
    {"id":"approve","type":"human_approval","on_approve":"renew","on_reject":"close_rejected"},
    {"id":"renew","type":"tool_call","tool":"license.renew","guards":{"reversible":true},"catch":"escalate","next":"assign"},
    {"id":"assign","type":"tool_call","tool":"license.assign","next":"verify"},
    {"id":"verify","type":"tool_call","tool":"license.verify_active","next":"close"},
    {"id":"close","type":"terminal","status":"success"},
    {"id":"close_rejected","type":"terminal","status":"rejected"} ],
  "compensation":[{"after":"renew","undo":"license.release_seat"}] }`,
    steps:[
      {id:'fetch', type:'tool_call', service:'servicenow', title:'Open the ticket', durationMs:1100,
        chat:{from:'user', text:"My AutoCAD licence has expired — I can't open my drawings."},
        output:'Ticket INC-4866 created'},
      {id:'check', type:'tool_call', service:'license', title:'Check the licence status', durationMs:1500,
        chat:{from:'zoe', text:"Thanks Omar — let me check your AutoCAD licence."},
        output:'Expired · renewable · seats available · £480/yr',
        inputs:{product:'AutoCAD', user:'omar.a'}, checked:'It can be renewed, and there’s a free seat'},
      {id:'decide', type:'choice', service:'sop', title:'Decide what to do', durationMs:1200,
        branch:'Renewable, but licence spend always needs a manager’s OK → ask for approval',
        output:'Routing to approval', guard:'Safety rule: any spend needs a human, even under the £500 limit'},
      {id:'approve', type:'human_approval', service:'human', title:"Wait for the manager's OK", durationMs:0,
        chat:{from:'zoe', text:"This needs a quick sign-off from your manager (£480/yr). I've asked them — one moment."},
        hitl:{ prompt:'Approve AutoCAD renewal for omar.a — £480/year?', onApprove:'renew', onReject:'close_rejected'},
        inputs:{product:'AutoCAD', cost:'£480/yr'} },
      {id:'renew', type:'tool_call', service:'license', title:'Renew the licence', durationMs:1600,
        chat:{from:'zoe', text:"Approved — renewing it now."},
        output:'Renewed · new expiry next year', guard:'Reversible · idempotent (won’t double-charge)'},
      {id:'assign', type:'tool_call', service:'license', title:'Assign it to Omar', durationMs:1100,
        output:'Assigned to omar.a'},
      {id:'verify', type:'tool_call', service:'license', title:"Check it's active", durationMs:1100,
        output:'Active ✓', checked:'Licence confirmed working'},
      {id:'close', type:'terminal', service:'servicenow', title:'Close the ticket', durationMs:1000,
        chat:{from:'zoe', text:"Done! Your AutoCAD is renewed and active — you’re good to go."},
        output:'Resolved · code: Solved'},
      /* reject branch target */
      {id:'close_rejected', type:'terminal', service:'servicenow', title:'Close — not approved', durationMs:1000,
        chat:{from:'zoe', text:"Your manager didn't approve the renewal this time. I've logged it and let you know who to contact."},
        output:'Closed · code: Not Authorised'},
    ],
    outcome:{ ticket:'INC-4866', resolution:'Solved', elapsedSec:96, automationPct:80, trueResolution:true,
      logs:['Ticket created','Matched recipe: license_expired','Licence renewable, £480/yr','Safety rule → manager approval','Approved','Renewed & assigned','Resolved'] } },
  /* 3 ───────────────── VPN DOWN (several AI workers check at once, then fix) */
  { id:'vpn_down', title:'VPN keeps dropping', icon:'🛰️', category:'Network', tier:'L2/L3', autonomy:'auto',
    channel:'chat', user:{name:'Lena M.', id:'lena.m', device:'LENA-LT-11'},
    intent:'VPN / connectivity', confidence:0.91,
    variables:[ {k:'user', v:'lena.m', src:'who raised the ticket'},
                {k:'tunnel', v:'ZPA-EU-WEST', src:'Zscaler'},
                {k:'device', v:'LENA-LT-11', src:'IT inventory (CMDB)'} ],
    sopId:'vpn_connectivity', sopVersion:'2',
    sopJson:`{ "sop_id":"vpn_connectivity","version":"2","autonomy":{"mode":"auto"},
  "states":[
    {"id":"fetch","type":"tool_call","tool":"servicenow.get_incident","next":"triage"},
    {"id":"triage","type":"parallel","branches":[
       {"agent":"identity_agent","goal":"account/MFA health"},
       {"agent":"network_agent","goal":"VPN tunnel state"},
       {"agent":"endpoint_agent","goal":"device health (read-only)"}],
       "merge":"llm_call:root_cause","next":"restart"},
    {"id":"restart","type":"script","tool":"dex.restart_vpn_client","next":"reauth"},
    {"id":"reauth","type":"tool_call","tool":"entra.force_reauth","next":"validate"},
    {"id":"validate","type":"tool_call","tool":"zscaler.validate_tunnel","next":"didItWork"},
    {"id":"didItWork","type":"choice","choices":[{"if":"!connected","next":"escalate"}],"default":"close"},
    {"id":"close","type":"terminal","status":"success"},
    {"id":"escalate","type":"tool_call","tool":"servicenow.escalate"} ] }`,
    steps:[
      {id:'fetch', type:'tool_call', service:'servicenow', title:'Open the ticket', durationMs:1000,
        chat:{from:'user', text:"Zscaler keeps disconnecting — I can't reach the CRM from home."},
        output:'Ticket INC-4902 created'},
      {id:'triage', type:'parallel', service:'reasoning', title:'Run 3 checks at the same time', durationMs:2200,
        chat:{from:'zoe', text:"Let me run a few checks together — one sec."},
        agents:[
          {service:'entra', title:'Check account & MFA', output:'Account healthy ✓'},
          {service:'zscaler', title:'Check the VPN tunnel', output:"Tunnel stuck 'reconnecting'"},
          {service:'dex', title:'Check the device (read-only)', output:'VPN client process hung'} ],
        output:'Combined → root cause: hung VPN client + stale session', checked:'Three AI workers, in parallel'},
      {id:'restart', type:'script', service:'dex', title:'Restart the VPN client on her laptop', durationMs:1700,
        output:'Client restarted', guard:'Read-only diagnosis first · safe, reversible action'},
      {id:'reauth', type:'tool_call', service:'entra', title:'Force a fresh sign-in', durationMs:1300,
        output:'Re-authenticated'},
      {id:'validate', type:'tool_call', service:'zscaler', title:'Check the tunnel is back', durationMs:1500,
        chat:{from:'zoe', text:"Tunnel's back up — try the CRM now."},
        output:'Connected · latency 41ms ✓', checked:'Service restored'},
      {id:'didItWork', type:'choice', service:'sop', title:'Did it work?', durationMs:900,
        branch:'Connected ✓ → close (if it had failed → hand to Network Engineering with the full trail)',
        output:'Recovered — no escalation needed'},
      {id:'close', type:'terminal', service:'servicenow', title:'Close the ticket', durationMs:1000,
        chat:{from:'user', text:"Working now, thank you!"},
        output:'Resolved · L3 escalation avoided'},
    ],
    outcome:{ ticket:'INC-4902', resolution:'Solved', elapsedSec:75, automationPct:100, trueResolution:true,
      logs:['Ticket created','3 AI workers triaged in parallel','Root cause: hung client','Restarted client + re-auth','Tunnel restored','Resolved in 75s'] } },
  /* 4 ───────────────── SOFTWARE REQUEST (needs approval, then auto-installs) */
  { id:'software_request', title:'Software request', icon:'📦', category:'Software', tier:'L2', autonomy:'hitl',
    channel:'chat', user:{name:'Raj P.', id:'raj.p', device:'RAJ-LT-09'},
    intent:'Software request', confidence:0.93,
    variables:[ {k:'product', v:'Adobe Photoshop', src:'the ticket'},
                {k:'user', v:'raj.p', src:'who raised the ticket'},
                {k:'role', v:'Design team', src:'Active Directory'},
                {k:'cost', v:'£20 / month', src:'License Manager'} ],
    sopId:'software_request', sopVersion:'1',
    sopJson:`{ "sop_id":"software_request","version":"1","autonomy":{"mode":"hitl"},
  "states":[
    {"id":"fetch","type":"tool_call","tool":"servicenow.get_request","next":"entitle"},
    {"id":"entitle","type":"tool_call","tool":"ad.check_entitlement","next":"avail"},
    {"id":"avail","type":"tool_call","tool":"license.check_availability","next":"approve"},
    {"id":"approve","type":"human_approval","on_approve":"deploy","on_reject":"close_rejected"},
    {"id":"deploy","type":"tool_call","tool":"intune.deploy_app","next":"confirm"},
    {"id":"confirm","type":"tool_call","tool":"intune.verify_install","next":"close"},
    {"id":"close","type":"terminal","status":"success"},
    {"id":"close_rejected","type":"terminal","status":"rejected"} ] }`,
    steps:[
      {id:'fetch', type:'tool_call', service:'servicenow', title:'Open the request', durationMs:1000,
        chat:{from:'user', text:"I need Photoshop for the new design project."},
        output:'Request REQ-2210 created'},
      {id:'entitle', type:'tool_call', service:'ad', title:"Check Raj's role", durationMs:1300,
        output:"Member of 'Design' ✓", inputs:{user:'raj.p'}, checked:'Eligible for design tools'},
      {id:'avail', type:'tool_call', service:'license', title:'Check licence availability & cost', durationMs:1300,
        output:'3 seats free · £20/mo'},
      {id:'approve', type:'human_approval', service:'human', title:"Manager's OK for the spend", durationMs:0,
        chat:{from:'zoe', text:"Raj's eligible and seats are free — I've asked his manager to approve the £20/mo."},
        hitl:{ prompt:'Approve Photoshop for raj.p — £20/month?', onApprove:'deploy', onReject:'close_rejected'} },
      {id:'deploy', type:'tool_call', service:'intune', title:"Install Photoshop on Raj's laptop", durationMs:1900,
        chat:{from:'zoe', text:"Approved — installing it on your laptop now, no action needed from you."},
        output:'Deploying… installed', guard:'Single device · standard package'},
      {id:'confirm', type:'tool_call', service:'intune', title:'Confirm it installed', durationMs:1100,
        output:'Installed ✓'},
      {id:'close', type:'terminal', service:'servicenow', title:'Close the request', durationMs:1000,
        chat:{from:'zoe', text:"Photoshop is installed and ready. Enjoy the new project!"},
        output:'Fulfilled'},
      {id:'close_rejected', type:'terminal', service:'servicenow', title:'Close — not approved', durationMs:1000,
        chat:{from:'zoe', text:"That wasn't approved this time — I've logged the reason on your request."},
        output:'Closed · Not Authorised'},
    ],
    outcome:{ ticket:'REQ-2210', resolution:'Fulfilled', elapsedSec:64, automationPct:85, trueResolution:true,
      logs:['Request created','Eligibility checked','Seats available','Manager approved','Installed via Intune','Fulfilled'] } },
  /* 5 ───────────────── NEW-JOINER ONBOARDING (a multi-step "saga" that can undo itself) */
  { id:'onboarding', title:'New joiner setup', icon:'🧑‍💼', category:'Lifecycle', tier:'L2', autonomy:'hitl',
    channel:'chat', user:{name:'Mariam (HR)', id:'hr.mariam', device:'—'},
    intent:'New employee onboarding', confidence:0.90,
    variables:[ {k:'new joiner', v:'yusuf.k', src:'HR request'},
                {k:'role', v:'Analyst', src:'HR request'},
                {k:'department', v:'Finance', src:'HR request'},
                {k:'start date', v:'Monday', src:'HR request'} ],
    sopId:'onboarding_jml', sopVersion:'2',
    sopJson:`{ "sop_id":"onboarding_jml","version":"2","autonomy":{"mode":"hitl"},
  "states":[
    {"id":"fetch","type":"tool_call","tool":"servicenow.get_request","next":"hr_ok"},
    {"id":"hr_ok","type":"human_approval","on_approve":"account","on_reject":"close_rejected"},
    {"id":"account","type":"tool_call","tool":"ad.create_account","next":"licences"},
    {"id":"licences","type":"tool_call","tool":"entra.assign_groups","next":"provision"},
    {"id":"provision","type":"parallel","branches":[
       {"tool":"intune.enrol_device"},{"tool":"m365.create_mailbox"}],"next":"notify"},
    {"id":"notify","type":"tool_call","tool":"servicenow.add_note","next":"close"},
    {"id":"close","type":"terminal","status":"success"},
    {"id":"close_rejected","type":"terminal","status":"rejected"} ],
  "compensation":[{"after":"account","undo":"ad.disable_account"},
                  {"after":"licences","undo":"entra.remove_groups"}] }`,
    steps:[
      {id:'fetch', type:'tool_call', service:'servicenow', title:'Open the request', durationMs:1000,
        chat:{from:'user', text:"New joiner: Yusuf Khan starts Monday as a Finance Analyst — please set him up."},
        output:'Request REQ-2301 created'},
      {id:'hr_ok', type:'human_approval', service:'human', title:'HR confirms the details', durationMs:0,
        chat:{from:'zoe', text:"Got it — I'll set up Yusuf (Analyst, Finance). Can you confirm the details to start?"},
        hitl:{ prompt:'Confirm onboarding for Yusuf Khan — Analyst, Finance, starts Monday?', onApprove:'account', onReject:'close_rejected'} },
      {id:'account', type:'tool_call', service:'ad', title:'Create his account', durationMs:1500,
        output:'Created yusuf.k', guard:'Part of a saga — undone automatically if a later step fails'},
      {id:'licences', type:'tool_call', service:'entra', title:'Assign licences & Finance groups', durationMs:1400,
        output:'M365 + Finance groups assigned'},
      {id:'provision', type:'parallel', service:'reasoning', title:'Set up device & mailbox (together)', durationMs:2100,
        agents:[ {service:'intune', title:'Enrol & set up laptop', output:'Enrolled · apps pushed'},
                 {service:'m365', title:'Create mailbox', output:'Mailbox ready'} ],
        output:'Device + mailbox ready'},
      {id:'notify', type:'tool_call', service:'servicenow', title:'Tell HR he’s ready', durationMs:1100,
        chat:{from:'zoe', text:"Yusuf is fully set up — account, licences, laptop and mailbox are ready for Monday."},
        output:'Work note added for HR'},
      {id:'close', type:'terminal', service:'servicenow', title:'Close the request', durationMs:1000,
        output:'Done · Day-one ready'},
      {id:'close_rejected', type:'terminal', service:'servicenow', title:'Close — details not confirmed', durationMs:1000,
        output:'Closed · awaiting HR'},
    ],
    outcome:{ ticket:'REQ-2301', resolution:'Done', elapsedSec:110, automationPct:90, trueResolution:true,
      logs:['Request created','HR confirmed','Account created','Licences + groups assigned','Device & mailbox provisioned','Day-one ready'] } },
  /* 6 ───────────────── SLOW LAPTOP (self-heal; also shows the proactive idea) */
  { id:'slow_laptop', title:'Slow laptop', icon:'🐌', category:'Endpoint', tier:'L2', autonomy:'auto',
    channel:'chat', user:{name:'Tom B.', id:'tom.b', device:'TOM-LT-07'},
    intent:'Slow device', confidence:0.94,
    variables:[ {k:'user', v:'tom.b', src:'who raised the ticket'},
                {k:'device', v:'TOM-LT-07', src:'IT inventory (CMDB)'} ],
    sopId:'slow_device', sopVersion:'1',
    sopJson:`{ "sop_id":"slow_device","version":"1","autonomy":{"mode":"auto"},
  "states":[
    {"id":"fetch","type":"tool_call","tool":"servicenow.get_incident","next":"diagnose"},
    {"id":"diagnose","type":"agent","agent":"endpoint_agent","next":"heal"},
    {"id":"heal","type":"script","tool":"dex.cleanup_and_restart","next":"policy"},
    {"id":"policy","type":"tool_call","tool":"intune.apply_perf_policy","next":"recheck"},
    {"id":"recheck","type":"choice","choices":[{"if":"!healthy","next":"escalate"}],"default":"close"},
    {"id":"close","type":"terminal","status":"success"} ] }`,
    steps:[
      {id:'fetch', type:'tool_call', service:'servicenow', title:'Open the ticket', durationMs:1000,
        chat:{from:'user', text:"My laptop is really slow today — everything's lagging."},
        output:'Ticket INC-4933 created'},
      {id:'diagnose', type:'agent', service:'dex', title:'Diagnose the device', durationMs:1900,
        chat:{from:'zoe', text:"Let me take a look at what's slowing it down."},
        output:'High memory (14 browser tabs) · a stuck update service · disk 96% full',
        checked:'Read-only health check via DEX telemetry'},
      {id:'heal', type:'script', service:'dex', title:'Clear temp files & restart the stuck service', durationMs:1700,
        output:'Freed 12 GB · service restarted', guard:'Safe, reversible cleanup'},
      {id:'policy', type:'tool_call', service:'intune', title:'Re-apply the right performance policy', durationMs:1300,
        output:'Policy applied'},
      {id:'recheck', type:'choice', service:'sop', title:'Back to normal?', durationMs:900,
        branch:'Healthy ✓ → close', output:'Performance restored'},
      {id:'close', type:'terminal', service:'servicenow', title:'Close the ticket', durationMs:1000,
        chat:{from:'zoe', text:"That should feel much faster now — I cleared 12 GB and fixed a stuck service. Ping me if it lags again."},
        output:'Resolved'},
    ],
    outcome:{ ticket:'INC-4933', resolution:'Solved', elapsedSec:58, automationPct:100, trueResolution:true,
      proactiveNote:'Zoé can run this same recipe automatically when it spots the warning signs — before Tom even notices.',
      logs:['Ticket created','Diagnosed: memory + disk + stuck service','Cleaned up · freed 12 GB','Policy re-applied','Resolved in 58s'] } },
  /* 7 ───────────────── HARDWARE FAULT (a remote fix fails → undo + hand to a human) */
  { id:'hardware_fault', title:'Laptop won’t boot', icon:'🔧', category:'Hardware', tier:'L3', autonomy:'auto',
    channel:'chat', user:{name:'Priya N.', id:'priya.n', device:'PRIYA-LT-22'},
    intent:'Hardware fault', confidence:0.72,
    variables:[ {k:'user', v:'priya.n', src:'who raised the ticket'},
                {k:'device', v:'PRIYA-LT-22', src:'IT inventory (CMDB)'},
                {k:'warranty', v:'in warranty', src:'Asset register'} ],
    sopId:'hardware_fault', sopVersion:'1',
    sopJson:`{ "sop_id":"hardware_fault","version":"1","autonomy":{"mode":"auto","min_confidence":0.85},
  "states":[
    {"id":"fetch","type":"tool_call","tool":"servicenow.get_incident","next":"diagnose"},
    {"id":"diagnose","type":"agent","agent":"endpoint_agent","next":"remote_fix"},
    {"id":"remote_fix","type":"script","tool":"dex.repair_boot","catch":"escalate","next":"verify"},
    {"id":"verify","type":"tool_call","tool":"dex.health_check","next":"close"},
    {"id":"escalate","type":"tool_call","tool":"servicenow.escalate","next":"handoff"},
    {"id":"handoff","type":"terminal","status":"handoff"} ],
  "compensation":[{"after":"remote_fix","undo":"dex.revert_repair"}] }`,
    steps:[
      {id:'fetch', type:'tool_call', service:'servicenow', title:'Open the ticket', durationMs:1000,
        chat:{from:'user', text:"My laptop won't turn on — black screen, nothing happens."},
        output:'Ticket INC-5012 created'},
      {id:'diagnose', type:'agent', service:'dex', title:'Diagnose remotely', durationMs:1900,
        chat:{from:'zoe', text:"Sorry to hear that, Priya — let me run a remote check."},
        output:'No OS response · disk not detected · likely hardware',
        checked:'Read-only telemetry — confidence only 72%', guard:'Low confidence → try one safe remote fix, then a human'},
      {id:'remote_fix', type:'script', service:'dex', title:'Try a safe remote boot repair', durationMs:1800,
        output:'Remote repair failed — disk not detected', status:'fail',
        guard:'Reversible attempt — auto-undone if it fails'},
    ],
    outcome:{ ticket:'INC-5012', resolution:'Escalated to Field Engineering', elapsedSec:44, automationPct:55, trueResolution:false,
      logs:['Ticket created','Diagnosed: likely hardware fault','Remote repair attempted','Repair failed → compensation (undo)','Handed to Field Engineering with full trail'] } },
];
/* expose for non-module scripts */
window.ZOE = { PLANES, SERVICES, MODULARITY, SCENARIOS };
